---
- hosts: all
  gather_facts: false
  # Generate password key 
  # python -c 'import crypt; print crypt.crypt("your-password", "$1$SomeSalt$")'
  vars:
    password_set: $1$SomeSalt$MTrfjA4WXc7dNfN6/aitu0
  tasks:
  - name: set a password 
    user: name=ubuntu update_password=always password={{ password_set }}
  - name: copy template
    template: src=sshd_config.j2 dest=/etc/ssh/sshd_config
    notify:
    - restart ssh
  handlers:
    - name: restart ssh
      service: name=ssh state=restarted
